// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDefaultOutputPath():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function SelectFile():Promise<Array<string>>;

export function UploadAndWatermark(arg1:Array<string>,arg2:string,arg3:string):Promise<Array<string>>;
